# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  release:
    types: 
      - published
      - edited

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Repo="${{ github.repository	}}"
        echo Ref="${{ github.ref }}"
        echo Actor="${{ github.actor }}"
        echo Workspace="${{ github.workspace }}"
        echo Sha="${{ github.sha }}"
        echo Rev=$(git rev-parse --short ${{ github.sha }})
        echo BuildDate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        
        IMAGE_NAME=${{ github.repository }}
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo VERSION=$VERSION
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo VERSION=$VERSION
        [ "$VERSION" == "master" ] && VERSION=latest
        
    - name: Display variables
      run: |
        echo IMAGE_NAME=$IMAGE_NAME
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        echo tag=$IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
