name: Build glibc multi arch using docker

on:
  workflow_dispatch:

jobs:
  build-glibc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create arm64v8 glibc builder image
      run: docker buildx build -t martinussuherman/alpine-glibc-builder:arm64v8 -f arm64v8/Dockerfile .

    - name: Run arm64v8 glibc builder image to build glibc
      run: docker run -it --rm martinussuherman/alpine-glibc-builder:arm64v8 -v ~/:/usr/glibc-compat/

    # - name: Upload build result as artifacts
    #   uses: actions/upload-artifact@v2
    #   with:	
    #     name: 'glibc artifacts'
    #     path: '~/glibc-bin-${{ steps.vardef.outputs.version }}.tar.gz'
