name: Build glibc multi arch

on:
  workflow_dispatch:

jobs:
  build-glibc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cross Compile Package for arm64v8
        run: |
          sudo apt install \
          gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu-dbg \
          build-essential

      - name: Variable Definition
        id: vardef
        run: |
          VER=2.33
          PREFIX=$HOME/build/glibc
          echo ::set-output name=version::${VER}
          echo ::set-output name=prefix::${PREFIX}

      - name: Clone glibc Repo
        run: |
          version=${{ steps.vardef.outputs.version }}
          mkdir $HOME/src
          cd $HOME/src
          git clone git://sourceware.org/git/glibc.git
          cd glibc
          git checkout release/$version/master
          chmod +x $HOME/src/glibc/configure

      - name: Building Glibc x86-64
        run: |
          version=${{ steps.vardef.outputs.version }}
          prefix=${{ steps.vardef.outputs.prefix }}
          mkdir -p $HOME/build/glibc
          cd $HOME/build/glibc
          $HOME/src/glibc/configure --prefix="$prefix" --libdir="$prefix/lib" --libexecdir="$prefix/lib" --enable-multi-arch --enable-stack-protector=strong
          make && make install
          tar --dereference --hard-dereference -zcf "$HOME/glibc-bin-x86-64-$version.tar.gz" "$prefix"

      - name: Building Glibc arm64v8
        run: |
          version=${{ steps.vardef.outputs.version }}
          prefix=${{ steps.vardef.outputs.prefix }}
          cd $HOME/build/glibc
          $HOME/src/glibc/configure --build x86_64-pc-linux-gnu --host aarch64-linux-gnu --enable-mpers=check --prefix="$prefix" --libdir="$prefix/lib" --libexecdir="$prefix/lib" --enable-stack-protector=strong
          make && make install
          tar --dereference --hard-dereference -zcf "$HOME/glibc-bin-aarch64-$version.tar.gz" "$prefix"

      - name: Upload build result as artifacts
        uses: actions/upload-artifact@v3
        with:	
          name: 'glibc artifacts'
          path: |
            '~/glibc-bin-x86-64-${{ steps.vardef.outputs.version }}.tar.gz'
            '~/glibc-bin-aarch64-${{ steps.vardef.outputs.version }}.tar.gz'
            