name: Build glibc multi arch

on:
  workflow_dispatch:

jobs:
  build-glibc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone glibc Repo
        run: |
          mkdir $HOME/src
          cd $HOME/src
          git clone git://sourceware.org/git/glibc.git
          cd glibc
          git checkout release/2.33/master
          chmod +x $HOME/src/glibc/configure

      - name: Building Glibc
        run: |
          prefix=$HOME/build/glibc
          mkdir -p $HOME/build/glibc
          cd $HOME/build/glibc
          $HOME/src/glibc/configure --prefix="$prefix" --libdir="$prefix/lib" --libexecdir="$prefix/lib" --enable-multi-arch --enable-stack-protector=strong
          make          
          tar --dereference --hard-dereference -zcf "$HOME/glibc-bin-$version.tar.gz" "$prefix"
