name: Build glibc multi arch using docker

on:
  workflow_dispatch:

jobs:
  build-glibc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push arm64v8 image
      uses: docker/build-push-action@v2
      with:
        file: ./builder-arm64v8/Dockerfile
        context: .
        platforms: linux/arm64
        push: true
        tags: martinussuherman/test-action:glibc-builder-arm64v8

    - name: Run arm64v8 glibc builder image
      run: |
        mkdir -p ~/artifact
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run martinussuherman/test-action:glibc-builder-arm64v8 -v ~/artifact:/glibc-tar

    - name: Upload build result as artifacts
      uses: actions/upload-artifact@v2
      with:	
        name: 'glibc-arm64v8'
        path: '~/artifact/glibc-bin-${{ steps.vardef.outputs.version }}.tar.gz'
