name: Build glibc multi arch

on:
  workflow_dispatch:

jobs:
  build-glibc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building Glibc
        id: glibcbuild
        run: |
          version=2.33
          prefix=/usr/glibc-compat
          wget -qO- "https://ftpmirror.gnu.org/libc/glibc-$version.tar.gz" | tar zxf -
          ./configure --prefix="$prefix" --libdir="$prefix/lib" --libexecdir="$prefix/lib" --enable-multi-arch --enable-stack-protector=strong
          make && make install
          tar --dereference --hard-dereference -zcf "/glibc-bin-$version.tar.gz" "$prefix"
