name: Test Action Variable

on:
  workflow_dispatch:

  release:
    types: 
    - published
    - edited

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Variable Definition
        id: vardef
        run: |
          IMG_NAME=${{ github.repository }}
          IMG_NAME=$(echo $IMG_NAME | sed -e 's!${{ github.repository_owner }}/!!')

          IMG_ID=docker.pkg.github.com/${{ github.repository }}/$IMG_NAME

          # Change all uppercase to lowercase
          IMG_ID=$(echo $IMG_ID | tr '[A-Z]' '[a-z]')
          IMG_URL=https://$IMG_ID

          # Strip git ref prefix from version
          IMG_VER=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMG_VER=$(echo $IMG_VER | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$IMG_VER" == "master" ] && IMG_VER=latest

          echo ::set-output name=imageId::${IMG_ID}
          echo ::set-output name=imageVersion::${IMG_VER}
          echo ::set-output name=imageUrl::${IMG_URL}
          echo ::set-output name=imageName::${IMG_NAME}

      - name: Another Variable Definition
        id: otherdef
        run: |
          DOCKER_IMAGE=myorg/myrepository
          VERSION=edge

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi

          TAGS="${DOCKER_IMAGE}:${VERSION}"

          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          fi

          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Display variables
        run: |
          echo version=${{ steps.vardef.otherdef.version }}
          echo tags=${{ steps.vardef.otherdef.tags }}
          echo created=${{ steps.vardef.otherdef.created }}
          echo imageId=${{ steps.vardef.outputs.imageId }}
          echo imageName=${{ steps.vardef.outputs.imageName }}
          echo imageUrl=${{ steps.vardef.outputs.imageUrl }}
          echo tag=${{ steps.vardef.outputs.imageName }} ${{ steps.vardef.outputs.imageId }}:${{ steps.vardef.outputs.imageVersion }}
          
